#!/bin/bash
#annihilate your workspace junk

VICTIMFILE="nukethis.txt"

if [ "$1" == "-r" ]
    then
        > nukethis.txt
        echo "targets (nukethis.txt) cleared"
fi
if [ "$1" == "-n" ]
    then
        if [ "$2" != "" ]
            then
                echo "$2" >> nukethis.txt
                echo "type $2 added"
        fi
        if [ "$2" == "" ]
            then
                echo "failed! next time input something (nuke -n [string value])"
        fi
fi
if [ "$1" != "-n" ] && [ "$1" != "-r" ]
    then
        #confirm they want to nuke the stuff
        
        entryct=0
        
        while read line; do
                    
            for entry in "$PWD"/*
            do
                if [[ "$entry" == *"$line"* ]] && [[ "$entry" != "nukethis.txt" ]] && [[ "$entry" != "nuke" ]]
                    then
                        let "entryct += 1"
                fi
            done
                    
        done < $VICTIMFILE
        
        if [[ "$1" != "" ]]
            then
                echo -e "continue with specific wipe (files containing $1)? (y/n)"
        else
            echo -e "continue with wipe ($entryct files)? (y/n)"
        fi
        read confirmwipe
        
        #check confirmation
        if [ "$confirmwipe" == "y" ]
            then
                #continue with the wipe
                
                if [[ "$1" != "" ]]
                    then
                        if [[ "$entry" == *"$1"* ]]
                            then
                                rm $entry
                                echo "BOOM! (files containing $1 were deleted)"
                        fi
                else
                    #read the file line by line
                    #check for matching files
                    while read line; do
                        
                        for entry in "$PWD"/*
                        do
                            if [[ "$entry" == *"$line"* ]] && [[ "$entry" != "nukethis.txt" ]] && [[ "$entry" != "nuke" ]]
                                then
                                    rm $entry
                                    echo "BOOM! ($entryct files deleted)"
                            fi
                        done
                            
                    done < $VICTIMFILE
                    
                fi
                
        fi
                
        if [ "$confirmwipe" == "n" ]
            then
                #don't go through with it
                echo "detonation cancelled"
        fi
                
        if [ "$confirmwipe" != "y" ] && [ "$confirmwipe" != "n" ]
            then
                #not valid input
                echo "failed! (next time, use y or n)"
        fi
        
        
fi
